package oauth

import (
	"crypto/rand"
	_ "embed"
	"encoding/base64"
	"log"
	"net/http"
	"text/template"
	"time"
)

//go:embed google_fcm.js
var googleFCMJSSource string

// google_fcm.js is a text/template, not raw JS: it has a single
// {{.Nonce}} substitution point for a server-generated nonce. text/template
// (not html/template) is intentional and safe here — the only value ever
// injected is a base64url-encoded random value generated by
// generateFCMNonce, which can never contain a quote, backslash, or other
// character that would need JS-string escaping. Do not extend this
// template to interpolate any other (especially user-controlled) value
// without switching to context-aware escaping.
var googleFCMTemplate = template.Must(template.New("google_fcm.js").Parse(googleFCMJSSource))

// GoogleFCMNonceCookie names the short-lived, HttpOnly cookie that binds a
// Google Identity Services (One Tap / FedCM) credential to the browser
// that actually requested it.
//
// The nonce is generated fresh on every request for this script, stored in
// this cookie, and also baked directly into the served JS, which passes it
// to google.accounts.id.initialize({ nonce }). Google embeds that value
// verbatim in the "nonce" claim of the resulting ID token. The OIDC
// credential-flow handler (method_oidc) verifies the token's nonce claim
// against this cookie before trusting the credential.
//
// Without this check, a valid credential obtained by an attacker for their
// own Google account could be replayed via a forged cross-site form POST
// to /api/login, logging a victim's browser into the attacker's account
// (login CSRF). Binding the nonce to a per-browser cookie prevents that,
// since the attacker cannot make the victim's browser present the nonce
// value that was issued to the attacker.
const GoogleFCMNonceCookie = "ls_oidc_fcm_nonce"

const googleFCMNonceTTL = 5 * time.Minute

func generateFCMNonce() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

type GoogleFCMJSRoute struct{}

func (g GoogleFCMJSRoute) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	nonce, err := generateFCMNonce()
	if err != nil {
		http.Error(w, "failed to prepare sign-in", http.StatusInternalServerError)
		return
	}

	http.SetCookie(w, &http.Cookie{
		Name:     GoogleFCMNonceCookie,
		Value:    nonce,
		Path:     "/api",
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteLaxMode,
		MaxAge:   int(googleFCMNonceTTL.Seconds()),
	})

	w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	// Every response embeds a fresh, single-use nonce, so this must never
	// be cached/shared across browsers by an intermediary or the browser's
	// own HTTP cache.
	w.Header().Set("Cache-Control", "no-store")

	if err := googleFCMTemplate.Execute(w, struct{ Nonce string }{Nonce: nonce}); err != nil {
		log.Println("[ls] failed to render google_fcm.js:", err)
	}
}
