name: Test Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Test
        run: go test -tags '!e2e' -v ./... -cover

  govuln:
    name: Govulncheck & Code Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write # needed to upload SARIF to Code Scanning
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck → SARIF
        run: govulncheck -format sarif -output govulncheck.sarif ./...

      - name: Upload govulncheck SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: govulncheck.sarif
